name: Periodic health check

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: check deployed url
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://aqueous-scrubland-74133.herokuapp.com/